apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=  # rootpass в base64
  MYSQL_USER: dG9kbw==  # todo в base64
  MYSQL_PASSWORD: dG9kb3Bhc3M=  # todopass в base64