apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  NAME: dG9kb2FwcA==  # todoapp в base64
  USER: dG9kbw==  # todo в base64
  PASSWORD: dG9kb3Bhc3M=  # todopass в base64
  HOST: bXlzcWwtMC5teXNxbC1oZWFkbGVzcy5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA==  # mysql-0.mysql-headless.mysql.svc.cluster.local в base64